### PR TITLE
Style MenuList

### PR DESCRIPTION
**Pull request by DymaxionMap**
My beautiful handiwork:

screen shot 2018-12-26 at 7 34 14 pm

### CODE REVIEW

**Review by Liamw0403 — APPROVED** [review]
beautiful

**Comment by chujacky** [comment]
looks really nice. Which font are you using?

**Comment by DymaxionMap** [comment]
I'm using Helvetica for the titles and Nunito Sans for the text. I looked at the GrubHub website with Chrome Dev Tools and they use GrubhubSans for the titles and graphik for the text, but they're both copyrighted fonts. I tried to find free ones that looked like them.

**Comment by chujacky** [comment]
I was also looking on Dev Tools and couldn't find them on google fonts. Thanks!

**Comment by DymaxionMap** [comment]
No problem

**Pull request merged**
