### PR TITLE
Slide Nav down or up depending on scroll position

### PR DESCRIPTION
**Pull request by DymaxionMap**

### CODE REVIEW

**Comment by Ammar-alnatsheh** [comment]
1-in client/components/AddItem/Nav.jsx file
do you mind to remove line 19 and 29// marcus said we are not suppose to have empty lines with in the same logic block

2-in client/components/AddItem/index.jsx file
i notice you use the parenthesis for one object from my end ESlint gave me a problem cause you can remove them since your logic stay with in one component 
ex: <OptionalChoices> component wrap everything in it. 

   : (
        <OptionalChoices
          optionalChoices={optionalChoices}
          updateOptionalChoice={this.updateOptionalChoice}
        />);

**Comment by DymaxionMap** [comment]
1) OK
2) Which line are you talking about?

**Comment by Ammar-alnatsheh** [comment]
line 149 to 153 and 159 to 160

line 163 is the proper way to do it

**Comment by DymaxionMap** [comment]
My ESLint gives me warnings when I delete the parentheses for lines 149-153 and 159-160 because even though they are one component each, they are on multiple lines. It wants me to wrap them in parentheses. 

This is the warning I get:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-wrap-multilines.md

**Comment by DymaxionMap** [comment]
Actually for 1) I think it's ok to have a space between the `from` and `to` blocks. If you look at the MDN example for keyframes, they have a space in between. I think it could be either way.
https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes

**Comment by DymaxionMap** [comment]
I do have an extra colon though. Let me send a new commit

**Pull request merged**
